language: java
jdk: oraclejdk8
sudo: true
before_install:
   - sudo apt-get install python3
   - sudo -H pip install websocket
   - sudo -H pip install faker
install: true
script: 
  - mvn clean integration-test
  - python3 ./pytest/websockettest.py
cache:
  directories:
  - $HOME/.m2
